--Region (all records)
INSERT INTO REGION (REGION_NAME) VALUES ('MidWest');
INSERT INTO REGION (REGION_NAME) VALUES ('NorthWest');
INSERT INTO REGION (REGION_NAME) VALUES ('South');
INSERT INTO REGION (REGION_NAME) VALUES ('SouthWest');
INSERT INTO REGION (REGION_NAME) VALUES ('SouthEast');
INSERT INTO REGION (REGION_NAME) VALUES ('New England');
INSERT INTO REGION (REGION_NAME) VALUES ('Great Lakes');

--Customer (all records)
INSERT INTO CUSTOMER (Customer_Name, CP_NAME, PHONE, EMAIL, RegionID) VALUES ('Airport Bikes', 'Tina', '622-091-9900', 'tina234@gmail.com', '1');
INSERT INTO CUSTOMER (Customer_Name, CP_NAME, PHONE, EMAIL, RegionID) VALUES ('Capital Bikes', 'Tony', '601-234-0911', 'tony2001@att.com', '4');
INSERT INTO CUSTOMER (Customer_Name, CP_NAME, PHONE, EMAIL, RegionID) VALUES ('Alster Cycling', 'Pam', '411-001-2145', 'moblig@icloud.com', '3');
INSERT INTO CUSTOMER (Customer_Name, CP_NAME, PHONE, EMAIL, RegionID) VALUES ('Run Swim Bike', 'Elly', '314-628-0032', 'macsmenace@ruwsbi.com', '1');

--Address_Type (all records)
INSERT INTO ADDRESS_TYPE (TYPE_CODE) VALUES ('Home');
INSERT INTO ADDRESS_TYPE (TYPE_CODE) VALUES ('Billing');
INSERT INTO ADDRESS_TYPE (TYPE_CODE) VALUES ('Shipping');
INSERT INTO ADDRESS_TYPE (TYPE_CODE) VALUES ('Home/Billing');
INSERT INTO ADDRESS_TYPE (TYPE_CODE) VALUES ('Home/Shipping');
INSERT INTO ADDRESS_TYPE (TYPE_CODE) VALUES ('Billing/Shipping');
INSERT INTO ADDRESS_TYPE (TYPE_CODE) VALUES ('Home/Billing/Shipping');

--Address (all records)
INSERT INTO ADDRESS (STREET_ADDRESS, CITY, STATE, ZIP_Code, COUNTRY, CUSTOMERID, TypeID) VALUES ('45020 Aviation Drive', 'Saint Louis', 'MO', '63166', 'US', '1', '1');
INSERT INTO ADDRESS (STREET_ADDRESS, CITY, STATE, ZIP_Code, COUNTRY, CUSTOMERID, TypeID) VALUES ('719 41 North Street', 'Saint Louis', 'MO', '63217', 'US', '1', '2');
INSERT INTO ADDRESS (STREET_ADDRESS, CITY, STATE, ZIP_Code, COUNTRY, CUSTOMERID, TypeID) VALUES ('5698 Elmonte Drive', 'Saint Louis', 'MO', '63132', 'US', '1', '3');
INSERT INTO ADDRESS (STREET_ADDRESS, CITY, STATE, ZIP_Code, COUNTRY, CUSTOMERID, TypeID) VALUES ('3235 Mi Casa Court', 'Birmingham', 'AL', '35203', 'US', '2', '7');
INSERT INTO ADDRESS (STREET_ADDRESS, CITY, STATE, ZIP_Code, COUNTRY, CUSTOMERID, TypeID) VALUES ('5698 Sunshine Drive', 'Chicago', 'IL', '60610', 'US', '3', '1');
INSERT INTO ADDRESS (STREET_ADDRESS, CITY, STATE, ZIP_Code, COUNTRY, CUSTOMERID, TypeID) VALUES ('12 State Street', 'Chicago', 'IL', '61610', 'US', '3', '6');
INSERT INTO ADDRESS (STREET_ADDRESS, CITY, STATE, ZIP_Code, COUNTRY, CUSTOMERID, TypeID) VALUES ('2530 Willow Court', 'Clearwater', 'FL', '33755', 'US', '4', '1');
INSERT INTO ADDRESS (STREET_ADDRESS, CITY, STATE, ZIP_Code, COUNTRY, CUSTOMERID, TypeID) VALUES ('2530 Willow Court', 'Clearwater', 'FL', '33755', 'US', '4', '2');
INSERT INTO ADDRESS (STREET_ADDRESS, CITY, STATE, ZIP_Code, COUNTRY, CUSTOMERID, TypeID) VALUES ('2530 Willow Court', 'Clearwater', 'FL', '33755', 'US', '4', '3');

--Category (all records)
INSERT INTO CATEGORY (CATEGORY_CODE, CATEGORY_NAME) VALUES ('ACC', 'Accessories');
INSERT INTO CATEGORY (CATEGORY_CODE, CATEGORY_NAME) VALUES ('TOU', 'Touring Bikes');
INSERT INTO CATEGORY (CATEGORY_CODE, CATEGORY_NAME) VALUES ('ROB', 'Road Bikes');
INSERT INTO CATEGORY (CATEGORY_CODE, CATEGORY_NAME) VALUES ('ORB', 'OffRoad Bikes');

--Product_Model (all records)
INSERT INTO PRODUCT_MODEL (MODEL_CODE, CATEGORYID) VALUES ('PRTR1000', '2');
INSERT INTO PRODUCT_MODEL (MODEL_CODE, CATEGORYID) VALUES ('DXTR1000', '2');
INSERT INTO PRODUCT_MODEL (MODEL_CODE, CATEGORYID) VALUES ('DXRD2000', '3');
INSERT INTO PRODUCT_MODEL (MODEL_CODE, CATEGORYID) VALUES ('ORHT2000', '4');
INSERT INTO PRODUCT_MODEL (MODEL_CODE, CATEGORYID) VALUES ('SHRT1000', '1');
INSERT INTO PRODUCT_MODEL (MODEL_CODE, CATEGORYID) VALUES ('RHMT1000', '1');
INSERT INTO PRODUCT_MODEL (MODEL_CODE, CATEGORYID) VALUES ('FAID1000', '1');
INSERT INTO PRODUCT_MODEL (MODEL_CODE, CATEGORYID) VALUES ('PRRD1000', '3');
INSERT INTO PRODUCT_MODEL (MODEL_CODE, CATEGORYID) VALUES ('PUMP1000', '1');

--Model_Text (all records)
INSERT INTO MODEL_TEXT (Description, ModelID) VALUES ('Professional Touring Bike', '1');
INSERT INTO MODEL_TEXT (Description, ModelID) VALUES ('Deluxe Touring Bike', '2');
INSERT INTO MODEL_TEXT (Description, ModelID) VALUES ('Road Bike Alu SRAM', '3');
INSERT INTO MODEL_TEXT (Description, ModelID) VALUES ('Off Road Bike Hard Tail SRAM', '4');
INSERT INTO MODEL_TEXT (Description, ModelID) VALUES ('T-shirt', '5');
INSERT INTO MODEL_TEXT (Description, ModelID) VALUES ('Road Helmet', '6');
INSERT INTO MODEL_TEXT (Description, ModelID) VALUES ('First Aid Kit', '7');
INSERT INTO MODEL_TEXT (Description, ModelID) VALUES ('Road Bike Carbon Shimano', '8');
INSERT INTO MODEL_TEXT (Description, ModelID) VALUES ('Air Pump', '9');

--Warehouse (all records)
INSERT INTO WAREHOUSE (Warehouseid, Warehouse_Code, Street_Address, City, State, ZIP_Code) VALUES ('1', 'ASTL', '13695 Rider Trail N ', ' Earth City', 'MO', '63045');

--Product_Color (all records)
INSERT INTO PRODUCT_COLOR (Color_Name) VALUES ('Silver');
INSERT INTO PRODUCT_COLOR (Color_Name) VALUES ('Blue');
INSERT INTO PRODUCT_COLOR (Color_Name) VALUES ('Black');
INSERT INTO PRODUCT_COLOR (Color_Name) VALUES ('Red');
INSERT INTO PRODUCT_COLOR (Color_Name) VALUES ('No Color');

--Product_Size (all records)
INSERT INTO PRODUCT_SIZE (Size_Value) VALUES ('28');
INSERT INTO PRODUCT_SIZE (Size_Value) VALUES ('30');
INSERT INTO PRODUCT_SIZE (Size_Value) VALUES ('32');
INSERT INTO PRODUCT_SIZE (Size_Value) VALUES ('No Size');

--Product_Built (all records)
INSERT INTO PRODUCT_BUILT (MODELID, COLORID, SIZEID, OH_QUANTITY, INITIAL_PRICE) VALUES ('1', '1', '1', '10', '2300');
INSERT INTO PRODUCT_BUILT (MODELID, COLORID, SIZEID, OH_QUANTITY, INITIAL_PRICE) VALUES ('1', '1', '2', '10', '2250');
INSERT INTO PRODUCT_BUILT (MODELID, COLORID, SIZEID, OH_QUANTITY, INITIAL_PRICE) VALUES ('1', '2', '1', '10', '2350');
INSERT INTO PRODUCT_BUILT (MODELID, COLORID, SIZEID, OH_QUANTITY, INITIAL_PRICE) VALUES ('1', '2', '2', '5', '2350');
INSERT INTO PRODUCT_BUILT (MODELID, COLORID, SIZEID, OH_QUANTITY, INITIAL_PRICE) VALUES ('1', '3', '3', '5', '2310');
INSERT INTO PRODUCT_BUILT (MODELID, COLORID, SIZEID, OH_QUANTITY, INITIAL_PRICE) VALUES ('2', '1', '1', '10', '2000');
INSERT INTO PRODUCT_BUILT (MODELID, COLORID, SIZEID, OH_QUANTITY, INITIAL_PRICE) VALUES ('2', '1', '2', '5', '2030');
INSERT INTO PRODUCT_BUILT (MODELID, COLORID, SIZEID, OH_QUANTITY, INITIAL_PRICE) VALUES ('2', '1', '3', '10', '2035');
INSERT INTO PRODUCT_BUILT (MODELID, COLORID, SIZEID, OH_QUANTITY, INITIAL_PRICE) VALUES ('2', '2', '1', '5', '1950');
INSERT INTO PRODUCT_BUILT (MODELID, COLORID, SIZEID, OH_QUANTITY, INITIAL_PRICE) VALUES ('2', '3', '2', '10', '1850');
INSERT INTO PRODUCT_BUILT (MODELID, COLORID, SIZEID, OH_QUANTITY, INITIAL_PRICE) VALUES ('3', '3', '2', '20', '3000');
INSERT INTO PRODUCT_BUILT (MODELID, COLORID, SIZEID, OH_QUANTITY, INITIAL_PRICE) VALUES ('3', '3', '3', '5', '3300');
INSERT INTO PRODUCT_BUILT (MODELID, COLORID, SIZEID, OH_QUANTITY, INITIAL_PRICE) VALUES ('3', '2', '1', '5', '3350');
INSERT INTO PRODUCT_BUILT (MODELID, COLORID, SIZEID, OH_QUANTITY, INITIAL_PRICE) VALUES ('4', '1', '1', '10', '3900');
INSERT INTO PRODUCT_BUILT (MODELID, COLORID, SIZEID, OH_QUANTITY, INITIAL_PRICE) VALUES ('4', '1', '2', '10', '3950');
INSERT INTO PRODUCT_BUILT (MODELID, COLORID, SIZEID, OH_QUANTITY, INITIAL_PRICE) VALUES ('4', '3', '1', '5', '3850');
INSERT INTO PRODUCT_BUILT (MODELID, COLORID, SIZEID, OH_QUANTITY, INITIAL_PRICE) VALUES ('4', '3', '2', '5', '3900');
INSERT INTO PRODUCT_BUILT (MODELID, COLORID, SIZEID, OH_QUANTITY, INITIAL_PRICE) VALUES ('5', '5', '4', '15', '80');
INSERT INTO PRODUCT_BUILT (MODELID, COLORID, SIZEID, OH_QUANTITY, INITIAL_PRICE) VALUES ('6', '5', '4', '15', '120');
INSERT INTO PRODUCT_BUILT (MODELID, COLORID, SIZEID, OH_QUANTITY, INITIAL_PRICE) VALUES ('7', '5', '4', '10', '55');
INSERT INTO PRODUCT_BUILT (MODELID, COLORID, SIZEID, OH_QUANTITY, INITIAL_PRICE) VALUES ('8', '1', '1', '5', '4500');
INSERT INTO PRODUCT_BUILT (MODELID, COLORID, SIZEID, OH_QUANTITY, INITIAL_PRICE) VALUES ('8', '1', '2', '10', '4000');
INSERT INTO PRODUCT_BUILT (MODELID, COLORID, SIZEID, OH_QUANTITY, INITIAL_PRICE) VALUES ('8', '1', '3', '5', '4700');
INSERT INTO PRODUCT_BUILT (MODELID, COLORID, SIZEID, OH_QUANTITY, INITIAL_PRICE) VALUES ('8', '2', '1', '5', '4700');
INSERT INTO PRODUCT_BUILT (MODELID, COLORID, SIZEID, OH_QUANTITY, INITIAL_PRICE) VALUES ('8', '2', '2', '5', '5000');
INSERT INTO PRODUCT_BUILT (MODELID, COLORID, SIZEID, OH_QUANTITY, INITIAL_PRICE) VALUES ('9', '5', '4', '10', '20');

--Sales_Transaction (all records)
INSERT INTO SALES_TRANSACTION (TDATE, TAMOUNT, CUSTOMERID) VALUES ('1/2/23', '18920', '1');
INSERT INTO SALES_TRANSACTION (TDATE, TAMOUNT, CUSTOMERID) VALUES ('1/2/23', '74800', '2');
INSERT INTO SALES_TRANSACTION (TDATE, TAMOUNT, CUSTOMERID) VALUES ('1/2/23', '153500', '3');
INSERT INTO SALES_TRANSACTION (TDATE, TAMOUNT, CUSTOMERID) VALUES ('1/2/23', '314400', '4');
INSERT INTO SALES_TRANSACTION (TDATE, TAMOUNT, CUSTOMERID) VALUES ('1/2/23', '24450', '1');
INSERT INTO SALES_TRANSACTION (TDATE, TAMOUNT, CUSTOMERID) VALUES ('1/2/23', '187200', '1');
INSERT INTO SALES_TRANSACTION (TDATE, TAMOUNT, CUSTOMERID) VALUES ('1/2/23', '217075', '2');
INSERT INTO SALES_TRANSACTION (TDATE, TAMOUNT, CUSTOMERID) VALUES ('1/2/23', '119475', '4');
INSERT INTO SALES_TRANSACTION (TDATE, TAMOUNT, CUSTOMERID) VALUES ('1/2/23', '191175', '3');
INSERT INTO SALES_TRANSACTION (TDATE, TAMOUNT, CUSTOMERID) VALUES ('1/2/23', '151975', '3');
INSERT INTO SALES_TRANSACTION (TDATE, TAMOUNT, CUSTOMERID) VALUES ('1/2/23', '122750', '3');

--Accounts_Receivable (all records)
INSERT INTO ACCOUNTS_RECEIVABLE (TID, DATE_RECORDED, AMOUNT, DATE_DUE, BALANCE_DUE) VALUES ('1', '1/2/23', '18920', '2/1/23', '18920');
INSERT INTO ACCOUNTS_RECEIVABLE (TID, DATE_RECORDED, AMOUNT, DATE_DUE, BALANCE_DUE) VALUES ('2', '1/2/23', '74800', '2/1/23', '74800');
INSERT INTO ACCOUNTS_RECEIVABLE (TID, DATE_RECORDED, AMOUNT, DATE_DUE, BALANCE_DUE) VALUES ('3', '1/2/23', '153500', '2/1/23', '153500');
INSERT INTO ACCOUNTS_RECEIVABLE (TID, DATE_RECORDED, AMOUNT, DATE_DUE, BALANCE_DUE) VALUES ('4', '1/2/23', '314400', '2/1/23', '157200');
INSERT INTO ACCOUNTS_RECEIVABLE (TID, DATE_RECORDED, AMOUNT, DATE_DUE, BALANCE_DUE) VALUES ('4', '1/2/23', '157200', '3/3/23', '157200');
INSERT INTO ACCOUNTS_RECEIVABLE (TID, DATE_RECORDED, AMOUNT, DATE_DUE, BALANCE_DUE) VALUES ('5', '1/2/23', '24450', '2/1/23', '24450');
INSERT INTO ACCOUNTS_RECEIVABLE (TID, DATE_RECORDED, AMOUNT, DATE_DUE, BALANCE_DUE) VALUES ('6', '1/2/23', '24450', '2/1/23', '24450');
INSERT INTO ACCOUNTS_RECEIVABLE (TID, DATE_RECORDED, AMOUNT, DATE_DUE, BALANCE_DUE) VALUES ('7', '1/2/23', '217075', '2/1/23', '108537.5');
INSERT INTO ACCOUNTS_RECEIVABLE (TID, DATE_RECORDED, AMOUNT, DATE_DUE, BALANCE_DUE) VALUES ('7', '1/2/23', '108537.5', '3/3/23', '108537.5');
INSERT INTO ACCOUNTS_RECEIVABLE (TID, DATE_RECORDED, AMOUNT, DATE_DUE, BALANCE_DUE) VALUES ('8', '1/2/23', '119475', '2/1/23', '119475');
INSERT INTO ACCOUNTS_RECEIVABLE (TID, DATE_RECORDED, AMOUNT, DATE_DUE, BALANCE_DUE) VALUES ('9', '1/2/23', '191175', '2/1/23', '191175');
INSERT INTO ACCOUNTS_RECEIVABLE (TID, DATE_RECORDED, AMOUNT, DATE_DUE, BALANCE_DUE) VALUES ('10', '1/2/23', '151975', '2/1/23', '151975');
INSERT INTO ACCOUNTS_RECEIVABLE (TID, DATE_RECORDED, AMOUNT, DATE_DUE, BALANCE_DUE) VALUES ('11', '1/2/23', '122750', '2/1/23', '122750');

--Transaction_line (all records)
INSERT INTO TRANSACTION_LINE (TID, PRODUCTID, QUANTITY, SALES_PRICE, DISCOUNT) VALUES ('1', '1', '3', '2300', '0');
INSERT INTO TRANSACTION_LINE (TID, PRODUCTID, QUANTITY, SALES_PRICE, DISCOUNT) VALUES ('1', '3', '5', '2350', '700');
INSERT INTO TRANSACTION_LINE (TID, PRODUCTID, QUANTITY, SALES_PRICE, DISCOUNT) VALUES ('1', '9', '20', '20', '60');
INSERT INTO TRANSACTION_LINE (TID, PRODUCTID, QUANTITY, SALES_PRICE, DISCOUNT) VALUES ('2', '1', '8', '2300', '400');
INSERT INTO TRANSACTION_LINE (TID, PRODUCTID, QUANTITY, SALES_PRICE, DISCOUNT) VALUES ('2', '2', '5', '2250', '700');
INSERT INTO TRANSACTION_LINE (TID, PRODUCTID, QUANTITY, SALES_PRICE, DISCOUNT) VALUES ('2', '9', '10', '1950', '250');
INSERT INTO TRANSACTION_LINE (TID, PRODUCTID, QUANTITY, SALES_PRICE, DISCOUNT) VALUES ('2', '18', '10', '80', '0');
INSERT INTO TRANSACTION_LINE (TID, PRODUCTID, QUANTITY, SALES_PRICE, DISCOUNT) VALUES ('2', '19', '10', '120', '0');
INSERT INTO TRANSACTION_LINE (TID, PRODUCTID, QUANTITY, SALES_PRICE, DISCOUNT) VALUES ('2', '25', '5', '5000', '500');
INSERT INTO TRANSACTION_LINE (TID, PRODUCTID, QUANTITY, SALES_PRICE, DISCOUNT) VALUES ('3', '17', '10', '3900', '500');
INSERT INTO TRANSACTION_LINE (TID, PRODUCTID, QUANTITY, SALES_PRICE, DISCOUNT) VALUES ('3', '18', '50', '80', '400');
INSERT INTO TRANSACTION_LINE (TID, PRODUCTID, QUANTITY, SALES_PRICE, DISCOUNT) VALUES ('3', '19', '30', '120', '0');
INSERT INTO TRANSACTION_LINE (TID, PRODUCTID, QUANTITY, SALES_PRICE, DISCOUNT) VALUES ('3', '21', '5', '4500', '200');
INSERT INTO TRANSACTION_LINE (TID, PRODUCTID, QUANTITY, SALES_PRICE, DISCOUNT) VALUES ('3', '22', '10', '4000', '500');
INSERT INTO TRANSACTION_LINE (TID, PRODUCTID, QUANTITY, SALES_PRICE, DISCOUNT) VALUES ('3', '23', '5', '4700', '500');
INSERT INTO TRANSACTION_LINE (TID, PRODUCTID, QUANTITY, SALES_PRICE, DISCOUNT) VALUES ('3', '24', '5', '4700', '500');
INSERT INTO TRANSACTION_LINE (TID, PRODUCTID, QUANTITY, SALES_PRICE, DISCOUNT) VALUES ('4', '6', '20', '2000', '0');
INSERT INTO TRANSACTION_LINE (TID, PRODUCTID, QUANTITY, SALES_PRICE, DISCOUNT) VALUES ('4', '7', '10', '2030', '0');
INSERT INTO TRANSACTION_LINE (TID, PRODUCTID, QUANTITY, SALES_PRICE, DISCOUNT) VALUES ('4', '8', '10', '2035', '0');
INSERT INTO TRANSACTION_LINE (TID, PRODUCTID, QUANTITY, SALES_PRICE, DISCOUNT) VALUES ('4', '9', '15', '1950', '0');
INSERT INTO TRANSACTION_LINE (TID, PRODUCTID, QUANTITY, SALES_PRICE, DISCOUNT) VALUES ('4', '12', '15', '3300', '0');
INSERT INTO TRANSACTION_LINE (TID, PRODUCTID, QUANTITY, SALES_PRICE, DISCOUNT) VALUES ('4', '14', '20', '3900', '0');
INSERT INTO TRANSACTION_LINE (TID, PRODUCTID, QUANTITY, SALES_PRICE, DISCOUNT) VALUES ('4', '16', '20', '3850', '0');
INSERT INTO TRANSACTION_LINE (TID, PRODUCTID, QUANTITY, SALES_PRICE, DISCOUNT) VALUES ('5', '1', '10', '2300', '100');
INSERT INTO TRANSACTION_LINE (TID, PRODUCTID, QUANTITY, SALES_PRICE, DISCOUNT) VALUES ('5', '18', '20', '80', '50');
INSERT INTO TRANSACTION_LINE (TID, PRODUCTID, QUANTITY, SALES_PRICE, DISCOUNT) VALUES ('5', '26', '10', '20', '0');
INSERT INTO TRANSACTION_LINE (TID, PRODUCTID, QUANTITY, SALES_PRICE, DISCOUNT) VALUES ('6', '5', '10', '2310', '0');
INSERT INTO TRANSACTION_LINE (TID, PRODUCTID, QUANTITY, SALES_PRICE, DISCOUNT) VALUES ('6', '6', '10', '2000', '0');
INSERT INTO TRANSACTION_LINE (TID, PRODUCTID, QUANTITY, SALES_PRICE, DISCOUNT) VALUES ('6', '7', '10', '2030', '0');
INSERT INTO TRANSACTION_LINE (TID, PRODUCTID, QUANTITY, SALES_PRICE, DISCOUNT) VALUES ('6', '13', '10', '3350', '0');
INSERT INTO TRANSACTION_LINE (TID, PRODUCTID, QUANTITY, SALES_PRICE, DISCOUNT) VALUES ('6', '21', '5', '4500', '100');
INSERT INTO TRANSACTION_LINE (TID, PRODUCTID, QUANTITY, SALES_PRICE, DISCOUNT) VALUES ('6', '22', '5', '4000', '100');
INSERT INTO TRANSACTION_LINE (TID, PRODUCTID, QUANTITY, SALES_PRICE, DISCOUNT) VALUES ('6', '23', '5', '4700', '100');
INSERT INTO TRANSACTION_LINE (TID, PRODUCTID, QUANTITY, SALES_PRICE, DISCOUNT) VALUES ('6', '25', '5', '5000', '400');
INSERT INTO TRANSACTION_LINE (TID, PRODUCTID, QUANTITY, SALES_PRICE, DISCOUNT) VALUES ('7', '6', '20', '4000', '500');
INSERT INTO TRANSACTION_LINE (TID, PRODUCTID, QUANTITY, SALES_PRICE, DISCOUNT) VALUES ('7', '9', '10', '1950', '0');
INSERT INTO TRANSACTION_LINE (TID, PRODUCTID, QUANTITY, SALES_PRICE, DISCOUNT) VALUES ('7', '11', '10', '3000', '0');
INSERT INTO TRANSACTION_LINE (TID, PRODUCTID, QUANTITY, SALES_PRICE, DISCOUNT) VALUES ('7', '17', '10', '3900', '200');
INSERT INTO TRANSACTION_LINE (TID, PRODUCTID, QUANTITY, SALES_PRICE, DISCOUNT) VALUES ('7', '20', '5', '55', '0');
INSERT INTO TRANSACTION_LINE (TID, PRODUCTID, QUANTITY, SALES_PRICE, DISCOUNT) VALUES ('7', '21', '5', '4500', '100');
INSERT INTO TRANSACTION_LINE (TID, PRODUCTID, QUANTITY, SALES_PRICE, DISCOUNT) VALUES ('7', '22', '5', '4000', '100');
INSERT INTO TRANSACTION_LINE (TID, PRODUCTID, QUANTITY, SALES_PRICE, DISCOUNT) VALUES ('7', '23', '5', '4700', '100');
INSERT INTO TRANSACTION_LINE (TID, PRODUCTID, QUANTITY, SALES_PRICE, DISCOUNT) VALUES ('7', '24', '5', '4700', '200');
INSERT INTO TRANSACTION_LINE (TID, PRODUCTID, QUANTITY, SALES_PRICE, DISCOUNT) VALUES ('8', '1', '10', '2300', '0');
INSERT INTO TRANSACTION_LINE (TID, PRODUCTID, QUANTITY, SALES_PRICE, DISCOUNT) VALUES ('8', '2', '10', '2250', '0');
INSERT INTO TRANSACTION_LINE (TID, PRODUCTID, QUANTITY, SALES_PRICE, DISCOUNT) VALUES ('8', '3', '10', '2350', '0');
INSERT INTO TRANSACTION_LINE (TID, PRODUCTID, QUANTITY, SALES_PRICE, DISCOUNT) VALUES ('8', '6', '10', '2000', '0');
INSERT INTO TRANSACTION_LINE (TID, PRODUCTID, QUANTITY, SALES_PRICE, DISCOUNT) VALUES ('8', '7', '10', '2030', '0');
INSERT INTO TRANSACTION_LINE (TID, PRODUCTID, QUANTITY, SALES_PRICE, DISCOUNT) VALUES ('8', '8', '5', '2035', '0');
INSERT INTO TRANSACTION_LINE (TID, PRODUCTID, QUANTITY, SALES_PRICE, DISCOUNT) VALUES ('9', '18', '20', '80', '0');
INSERT INTO TRANSACTION_LINE (TID, PRODUCTID, QUANTITY, SALES_PRICE, DISCOUNT) VALUES ('9', '19', '10', '120', '0');
INSERT INTO TRANSACTION_LINE (TID, PRODUCTID, QUANTITY, SALES_PRICE, DISCOUNT) VALUES ('9', '20', '5', '55', '0');
INSERT INTO TRANSACTION_LINE (TID, PRODUCTID, QUANTITY, SALES_PRICE, DISCOUNT) VALUES ('9', '21', '10', '4500', '0');
INSERT INTO TRANSACTION_LINE (TID, PRODUCTID, QUANTITY, SALES_PRICE, DISCOUNT) VALUES ('9', '23', '10', '4700', '200');
INSERT INTO TRANSACTION_LINE (TID, PRODUCTID, QUANTITY, SALES_PRICE, DISCOUNT) VALUES ('9', '24', '10', '4700', '200');
INSERT INTO TRANSACTION_LINE (TID, PRODUCTID, QUANTITY, SALES_PRICE, DISCOUNT) VALUES ('9', '25', '10', '5000', '500');
INSERT INTO TRANSACTION_LINE (TID, PRODUCTID, QUANTITY, SALES_PRICE, DISCOUNT) VALUES ('9', '26', '10', '20', '0');
INSERT INTO TRANSACTION_LINE (TID, PRODUCTID, QUANTITY, SALES_PRICE, DISCOUNT) VALUES ('10', '1', '10', '2300', '200');
INSERT INTO TRANSACTION_LINE (TID, PRODUCTID, QUANTITY, SALES_PRICE, DISCOUNT) VALUES ('10', '2', '10', '2250', '200');
INSERT INTO TRANSACTION_LINE (TID, PRODUCTID, QUANTITY, SALES_PRICE, DISCOUNT) VALUES ('10', '3', '10', '2350', '200');
INSERT INTO TRANSACTION_LINE (TID, PRODUCTID, QUANTITY, SALES_PRICE, DISCOUNT) VALUES ('10', '4', '10', '2350', '200');
INSERT INTO TRANSACTION_LINE (TID, PRODUCTID, QUANTITY, SALES_PRICE, DISCOUNT) VALUES ('10', '5', '5', '2310', '100');
INSERT INTO TRANSACTION_LINE (TID, PRODUCTID, QUANTITY, SALES_PRICE, DISCOUNT) VALUES ('10', '6', '5', '2000', '100');
INSERT INTO TRANSACTION_LINE (TID, PRODUCTID, QUANTITY, SALES_PRICE, DISCOUNT) VALUES ('10', '7', '5', '2030', '100');
INSERT INTO TRANSACTION_LINE (TID, PRODUCTID, QUANTITY, SALES_PRICE, DISCOUNT) VALUES ('10', '8', '5', '2035', '100');
INSERT INTO TRANSACTION_LINE (TID, PRODUCTID, QUANTITY, SALES_PRICE, DISCOUNT) VALUES ('10', '9', '5', '1950', '100');
INSERT INTO TRANSACTION_LINE (TID, PRODUCTID, QUANTITY, SALES_PRICE, DISCOUNT) VALUES ('10', '10', '5', '1850', '100');
INSERT INTO TRANSACTION_LINE (TID, PRODUCTID, QUANTITY, SALES_PRICE, DISCOUNT) VALUES ('11', '12', '5', '3300', '500');
INSERT INTO TRANSACTION_LINE (TID, PRODUCTID, QUANTITY, SALES_PRICE, DISCOUNT) VALUES ('11', '13', '5', '3350', '500');
INSERT INTO TRANSACTION_LINE (TID, PRODUCTID, QUANTITY, SALES_PRICE, DISCOUNT) VALUES ('11', '14', '5', '3900', '500');
INSERT INTO TRANSACTION_LINE (TID, PRODUCTID, QUANTITY, SALES_PRICE, DISCOUNT) VALUES ('11', '15', '5', '3950', '500');
INSERT INTO TRANSACTION_LINE (TID, PRODUCTID, QUANTITY, SALES_PRICE, DISCOUNT) VALUES ('11', '16', '5', '3850', '500');
INSERT INTO TRANSACTION_LINE (TID, PRODUCTID, QUANTITY, SALES_PRICE, DISCOUNT) VALUES ('11', '17', '5', '3900', '500');
INSERT INTO TRANSACTION_LINE (TID, PRODUCTID, QUANTITY, SALES_PRICE, DISCOUNT) VALUES ('11', '11', '5', '3000', '500');

--Inventory
DECLARE
    i number(3);
    SN number;
    ROWPRO number(3);
    temp number;
BEGIN
--ProductID = 1-3 (PL/SQL)
    SN:= 1234560;
    ROWPRO := 1;
    temp:= SN;
    <<loop>>
    FOR i IN 1..30 LOOP
        IF SN-10 = temp Then
            temp:= SN;
            ROWPRO:= ROWPRO + 1;
        END IF;
        SN:= SN + 1;
        INSERT INTO INVENTORY(SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES (SN, 1, ROWPRO, 1, ROWPRO);
    END LOOP;
END;
/

--Inventory (all remaining records)
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234591', '1', '4', '1', '4');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234592', '1', '4', '1', '4');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234593', '1', '4', '1', '4');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234594', '1', '4', '1', '4');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234595', '1', '4', '1', '4');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234596', '1', '5', '1', '5');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234597', '1', '5', '1', '5');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234598', '1', '5', '1', '5');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234599', '1', '5', '1', '5');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234600', '1', '5', '1', '5');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234601', '1', '6', '1', '6');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234602', '1', '6', '1', '6');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234603', '1', '6', '1', '6');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234604', '1', '6', '1', '6');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234605', '1', '6', '1', '6');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234606', '1', '6', '1', '6');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234607', '1', '6', '1', '6');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234608', '1', '6', '1', '6');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234609', '1', '6', '1', '6');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234610', '1', '6', '1', '6');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234611', '1', '7', '1', '7');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234612', '1', '7', '1', '7');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234613', '1', '7', '1', '7');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234614', '1', '7', '1', '7');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234615', '1', '7', '1', '7');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234616', '1', '8', '1', '8');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234617', '1', '8', '1', '8');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234618', '1', '8', '1', '8');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234619', '1', '8', '1', '8');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234620', '1', '8', '1', '8');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234621', '1', '8', '1', '8');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234622', '1', '8', '1', '8');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234623', '1', '8', '1', '8');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234624', '1', '8', '1', '8');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234625', '1', '8', '1', '8');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234626', '1', '9', '1', '9');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234627', '1', '9', '1', '9');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234628', '1', '9', '1', '9');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234629', '1', '9', '1', '9');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234630', '1', '9', '1', '9');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234631', '1', '10', '1', '10');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234632', '1', '10', '1', '10');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234633', '1', '10', '1', '10');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234634', '1', '10', '1', '10');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234635', '1', '10', '1', '10');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234636', '1', '10', '1', '10');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234637', '1', '10', '1', '10');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234638', '1', '10', '1', '10');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234639', '1', '10', '1', '10');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234640', '1', '10', '1', '10');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234641', '2', '1', '1', '11');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234642', '2', '1', '1', '11');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234643', '2', '1', '1', '11');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234644', '2', '1', '1', '11');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234645', '2', '1', '1', '11');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234646', '2', '1', '1', '11');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234647', '2', '1', '1', '11');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234648', '2', '1', '1', '11');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234649', '2', '1', '1', '11');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234650', '2', '1', '1', '11');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234651', '2', '1', '1', '11');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234652', '2', '1', '1', '11');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234653', '2', '1', '1', '11');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234654', '2', '1', '1', '11');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234655', '2', '1', '1', '11');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234656', '2', '1', '1', '11');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234657', '2', '1', '1', '11');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234658', '2', '1', '1', '11');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234659', '2', '1', '1', '11');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234660', '2', '1', '1', '11');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234661', '2', '2', '1', '12');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234662', '2', '2', '1', '12');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234663', '2', '2', '1', '12');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234664', '2', '2', '1', '12');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234665', '2', '2', '1', '12');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234666', '2', '3', '1', '13');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234667', '2', '3', '1', '13');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234668', '2', '3', '1', '13');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234669', '2', '3', '1', '13');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234670', '2', '3', '1', '13');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234671', '2', '4', '1', '14');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234672', '2', '4', '1', '14');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234673', '2', '4', '1', '14');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234674', '2', '4', '1', '14');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234675', '2', '4', '1', '14');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234676', '2', '4', '1', '14');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234677', '2', '4', '1', '14');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234678', '2', '4', '1', '14');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234679', '2', '4', '1', '14');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234680', '2', '4', '1', '14');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234681', '2', '5', '1', '15');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234682', '2', '5', '1', '15');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234683', '2', '5', '1', '15');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234684', '2', '5', '1', '15');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234685', '2', '5', '1', '15');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234686', '2', '5', '1', '15');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234687', '2', '5', '1', '15');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234688', '2', '5', '1', '15');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234689', '2', '5', '1', '15');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234690', '2', '5', '1', '15');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234691', '2', '6', '1', '16');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234692', '2', '6', '1', '16');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234693', '2', '6', '1', '16');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234694', '2', '6', '1', '16');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234695', '2', '6', '1', '16');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234696', '2', '7', '1', '17');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234697', '2', '7', '1', '17');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234698', '2', '7', '1', '17');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234699', '2', '7', '1', '17');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234700', '2', '7', '1', '17');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234701', '5', '1', '1', '18');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234702', '5', '1', '1', '18');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234703', '5', '1', '1', '18');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234704', '5', '1', '1', '18');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234705', '5', '1', '1', '18');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234706', '5', '1', '1', '18');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234707', '5', '1', '1', '18');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234708', '5', '1', '1', '18');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234709', '5', '1', '1', '18');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234710', '5', '1', '1', '18');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234711', '5', '1', '1', '18');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234712', '5', '1', '1', '18');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234713', '5', '1', '1', '18');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234714', '5', '1', '1', '18');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234715', '5', '1', '1', '18');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234716', '5', '2', '1', '19');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234717', '5', '2', '1', '19');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234718', '5', '2', '1', '19');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234719', '5', '2', '1', '19');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234720', '5', '2', '1', '19');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234721', '5', '2', '1', '19');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234722', '5', '2', '1', '19');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234723', '5', '2', '1', '19');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234724', '5', '2', '1', '19');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234725', '5', '2', '1', '19');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234726', '5', '2', '1', '19');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234727', '5', '2', '1', '19');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234728', '5', '2', '1', '19');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234729', '5', '2', '1', '19');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234730', '5', '2', '1', '19');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234731', '5', '3', '1', '20');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234732', '5', '3', '1', '20');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234733', '5', '3', '1', '20');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234734', '5', '3', '1', '20');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234735', '5', '3', '1', '20');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234736', '5', '3', '1', '20');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234737', '5', '3', '1', '20');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234738', '5', '3', '1', '20');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234739', '5', '3', '1', '20');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234740', '5', '3', '1', '20');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234741', '2', '8', '1', '21');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234742', '2', '8', '1', '21');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234743', '2', '8', '1', '21');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234744', '2', '8', '1', '21');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234745', '2', '8', '1', '21');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234746', '2', '9', '1', '22');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234747', '2', '9', '1', '22');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234748', '2', '9', '1', '22');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234749', '2', '9', '1', '22');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234750', '2', '9', '1', '22');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234751', '2', '9', '1', '22');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234752', '2', '9', '1', '22');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234753', '2', '9', '1', '22');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234754', '2', '9', '1', '22');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234755', '2', '9', '1', '22');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234756', '2', '10', '1', '23');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234757', '2', '10', '1', '23');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234758', '2', '10', '1', '23');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234759', '2', '10', '1', '23');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234760', '2', '10', '1', '23');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234761', '3', '1', '1', '24');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234762', '3', '1', '1', '24');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234763', '3', '1', '1', '24');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234764', '3', '1', '1', '24');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234765', '3', '1', '1', '24');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234766', '3', '2', '1', '25');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234767', '3', '2', '1', '25');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234768', '3', '2', '1', '25');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234769', '3', '2', '1', '25');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234770', '3', '2', '1', '25');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234771', '5', '4', '1', '26');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234772', '5', '4', '1', '26');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234773', '5', '4', '1', '26');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234774', '5', '4', '1', '26');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234775', '5', '4', '1', '26');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234776', '5', '4', '1', '26');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234777', '5', '4', '1', '26');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234778', '5', '4', '1', '26');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234779', '5', '4', '1', '26');
INSERT INTO INVENTORY (SERIAL_NO, AISLE_NO, ROW_NO, WAREHOUSEID, PRODUCTID) VALUES ('1234780', '5', '4', '1', '26');

--Price
DECLARE 
   i number(3); 
BEGIN 
--1-10
   << loop  >> 
   FOR i IN 1..10 LOOP 
      insert into price(price, inventoryid) values(2300,i);
   END loop; 
--11-20
   << loop  >> 
   FOR i IN 11..20 LOOP  
     Insert into PRICE (price, inventoryid) 
           values(2250,i);
   END loop;
--21-35
   << loop  >> 
   FOR i IN 21..35 LOOP  
     Insert into PRICE (price, inventoryid) 
           values(2350,i);
   END loop;
--36-40
   << loop  >> 
   FOR i IN 36..40 LOOP  
     Insert into PRICE (price, inventoryid) 
           values(2310,i);
   END loop;
--41-50
   << loop  >> 
   FOR i IN 41..50 LOOP  
     Insert into PRICE (price, inventoryid) 
           values(2000,i);
   END loop;
--51-55
   << loop  >> 
   FOR i IN 51..55 LOOP  
     Insert into PRICE (price, inventoryid) 
           values(2030,i);
   END loop;
--56-65
   << loop  >> 
   FOR i IN 56..65 LOOP  
     Insert into PRICE (price, inventoryid) 
           values(2035,i);
   END loop;
--66-70
   << loop  >> 
   FOR i IN 66..70 LOOP  
     Insert into PRICE (price, inventoryid) 
           values(1950,i);
   END loop;
--71-80
   << loop  >> 
   FOR i IN 71..80 LOOP  
     Insert into PRICE (price, inventoryid) 
           values(1850,i);
   END loop;
--81-100
   << loop  >> 
   FOR i IN 81..100 LOOP  
     Insert into PRICE (price, inventoryid) 
           values(3000,i);
   END loop;
--101-110
   << loop  >> 
   FOR i IN 101..110 LOOP  
     Insert into PRICE (price, inventoryid) 
           values(3350,i);
   END loop;
--111-120
   << loop  >> 
   FOR i IN 111..120 LOOP  
     Insert into PRICE (price, inventoryid) 
           values(3900,i);
   END loop;
--121-130
   << loop  >> 
   FOR i IN 121..130 LOOP  
     Insert into PRICE (price, inventoryid) 
           values(3950,i);
   END loop;
--131-135
   << loop  >> 
   FOR i IN 131..135 LOOP  
     Insert into PRICE (price, inventoryid) 
           values(3850,i);
   END loop;
--136-140
   << loop  >> 
   FOR i IN 136..140 LOOP  
     Insert into PRICE (price, inventoryid) 
           values(3900,i);
   END loop;
--141-155
   << loop  >> 
   FOR i IN 141..155 LOOP  
     Insert into PRICE (price, inventoryid) 
           values(80,i);
   END loop;
--156-170
   << loop  >> 
   FOR i IN 156..170 LOOP  
     Insert into PRICE (price, inventoryid) 
           values(120,i);
   END loop;
--171-180
   << loop  >> 
   FOR i IN 171..180 LOOP  
     Insert into PRICE (price, inventoryid) 
           values(55,i);
   END loop;
--181-185
   << loop  >> 
   FOR i IN 181..185 LOOP  
     Insert into PRICE (price, inventoryid) 
           values(4500,i);
   END loop;
--186-195
   << loop  >> 
   FOR i IN 186..195 LOOP  
     Insert into PRICE (price, inventoryid) 
           values(4000,i);
   END loop;
--196-205
   << loop  >> 
   FOR i IN 196..205 LOOP  
     Insert into PRICE (price, inventoryid) 
           values(4700,i);
   END loop;
--206-210
   << loop  >> 
   FOR i IN 206..210 LOOP  
     Insert into PRICE (price, inventoryid) 
           values(5000,i);
   END loop;
--211-220
   << loop  >> 
   FOR i IN 211..220 LOOP  
     Insert into PRICE (price, inventoryid) 
           values(20,i);
   END loop;
END;
/
