--a. List of customers for each region, with region name and customer name.
SELECT C.CUSTOMER_NAME, R.REGION_NAME FROM CUSTOMER C JOIN REGION R ON C.REGIONID=R.REGIONID ORDER BY R.REGION_NAME;
--b. List of customer name, address, and address type code for Midwest.
SELECT C.CUSTOMER_NAME, A.STREET_ADDRESS, A.ZIP_CODE, A.STATE, A.CITY, A.COUNTRY, T.TYPE_CODE FROM CUSTOMER C JOIN ADDRESS A ON C.CUSTOMERID=A.CUSTOMERID JOIN ADDRESS_TYPE T ON T.TYPEID=A.TYPEID JOIN REGION R ON R.REGIONID=C.REGIONID WHERE R.REGION_NAME='MidWest';
--c. List all regions with the count of their customers.
SELECT C.REGIONID, R.REGION_NAME, SUM(C.CUSTOMERID) AS "NO. OF CUSTOMERS" FROM CUSTOMER C JOIN REGION R ON C.REGIONID=R.REGIONID GROUP BY C.REGIONID, R.REGION_NAME;
--d. Region with the highest number of customer. A sorted list is not the answer!
SELECT REGIONID, REGION_NAME, NUM FROM (SELECT C.REGIONID, R.REGION_NAME, COUNT(C.CUSTOMERID) AS NUM FROM CUSTOMER C JOIN REGION R ON C.REGIONID=R.REGIONID GROUP BY C.REGIONID, R.REGION_NAME ORDER BY NUM DESC) where rownum=1
